version: "2.0"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - myNetwork
  kafka:
    image:  wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - 9092:9092
    links:
      - zookeeper
    networks:
      - myNetwork
    
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "demo-topic:3:1"
      

  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - kafka
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge